#!/usr/bin/env python3
"""Calibrate LowThrustTransfer-v2 with public optimization and independent dynamics.

The stored classical controls were generated by one finite-difference regularized
Gauss--Newton procedure using only the public inputs printed in Task.md.  They are replayed here
to make the calibration deterministic.  They are feasible local witnesses, not global optima,
and they are kept outside the task oracle so they cannot define the score normalization.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import math
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
from scipy.integrate import solve_ivp


ROOT = Path(__file__).resolve().parent.parent
TASK = ROOT / "benchmarks/Engineering/LowThrustTransfer"
sys.path.insert(0, str(ROOT))

from frontier_science.provenance import finalize_report_trust, source_provenance  # noqa: E402


# Order matches public_instances(), not private split labels.  Every result was produced by the
# same public finite-difference Gauss--Newton method with projection onto the continuous thrust
# bound.  The calibration report records that these are offline local witnesses.
CLASSICAL_COEFFICIENTS = (
    (
        (0.4398216715072041, -0.023139594243681384, -0.018052007782075184,
         0.04426405804279566, -0.029502301163080433, 0.038443001028040345,
         0.006029988841884995),
        (0.19829820520172703, -0.014802165625459596, 0.0001439899509500086,
         0.004193649415115254, -0.030373660155070068, 0.03291372031213134,
         0.016079778805260615),
        (0.6828757112687464, -0.007174203373369857, 0.010426778523177662,
         -0.028950417361153752, 0.02855374832053447, 0.028879327060506117,
         0.02506138425612715),
        (0.8737175977492777, 0.01664513246338786, 0.0005670722789528548,
         -0.0004280147403447057, 0.02494289630910969, 0.03949968188458198,
         0.03536667261673537),
    ),
    (
        (-0.2383986631890234, 0.11457921048237366, 0.02742997018061498,
         -0.043662929034506914, 0.1422725747831814, -0.15251808197242342,
         -0.09842379360619957),
        (-0.24244528382505806, 0.10635442038331097, 0.007367299828648903,
         -0.01819010607152065, 0.13457148378338796, -0.13141409838979223,
         -0.1243885777351414),
        (-0.4119255031437041, 0.0973558907241651, -0.00936520222558993,
         -0.0061949485820532125, 0.12765196375041352, -0.1027117391530521,
         -0.14276211476783274),
        (-0.5827697074556991, 0.08548902746979499, -0.01812241429688756,
         0.007482265664506117, 0.10688921963255782, -0.07014607548789471,
         -0.154389449211637),
    ),
    (
        (0.07403830152504112, 0.16615662040944346, 0.02556228937308525,
         -0.05993716174726154, 0.3214809179073901, 0.08202608622163961,
         -0.05169001970280843),
        (0.1015477835999014, 0.165839433925742, -0.016017715248712813,
         0.00790059122690195, 0.31855396925114887, 0.09104151662379954,
         -0.03371360121229604),
        (0.3116313847235371, 0.15590881815198823, -0.057149701370022774,
         0.07349684136667337, 0.2963779796625725, 0.09492996314062986,
         -0.01431948981100439),
        (0.5648465321250131, 0.13586469549495153, -0.09455644763053232,
         0.12706752695329723, 0.25920382420256305, 0.09469355853687346,
         0.005047019729794335),
    ),
    (
        (-0.31196624788480415, -0.006831120897599647, 0.027588265410733486,
         0.04154427309546492, 0.03600777865774509, 0.5219731280596254,
         0.1322027320274457),
        (0.5978404445152078, 0.009391685032871171, -0.01541814718360441,
         -0.02355137312437972, 0.018825102983049943, 0.3589230900922435,
         0.3902773632083788),
        (0.1920912595236166, 0.0019800514464419078, -0.00941470161991535,
         -0.005912000860162886, 0.01652004023690195, 0.206271887140686,
         0.5319615253841741),
        (0.5063761388763327, -0.004194835189112678, -0.006974841585763128,
         -0.012817083869844745, 0.014667885681699279, 0.01063964871110501,
         0.5723457996296072),
    ),
    (
        (-0.19164377657648174, -0.040617584305041976, -0.01708834288165301,
         0.010634019265636768, -0.04343237337122927, -0.16407471107028218,
         -0.27107193696469545),
        (-0.1801164171047474, -0.04134765508951899, -0.02530793311916118,
         -0.013197650160471593, -0.0459038286067486, -0.1303486659779855,
         -0.28345329436142547),
        (-0.2557489056948087, -0.04216348318855184, -0.03132866692468865,
         -0.026278015350920024, -0.04426644587796097, -0.09793328476513906,
         -0.2966305476799403),
        (-0.2172863853449047, -0.04204609400505333, -0.023664996654118253,
         -0.03148617355499938, -0.04566065825177169, -0.06527974422612039,
         -0.30741706524262497),
    ),
    (
        (0.25625219518547865, -0.07685041103325134, 0.017450884228130573,
         0.03838987132864972, -0.15819626955190957, 0.3506581926920345,
         0.18395812954843824),
        (0.24003197876420132, -0.06608621465109295, 0.019321867564717928,
         -0.004294914687438771, -0.1571969394776472, 0.31125930938080665,
         0.23464568731553076),
        (0.40634838915187055, -0.06525450571957402, 0.015923299131591146,
         -0.058778044898788635, -0.13252631294382927, 0.26516447642019003,
         0.27898329728436017),
        (0.46001010788674074, -0.06653022107878305, 0.016892439694924266,
         -0.10893439559747443, -0.09256338627087653, 0.207797938218935,
         0.31162594964701473),
    ),
)


def _load_oracle():
    path = TASK / "verification/evaluator.py"
    spec = importlib.util.spec_from_file_location(
        "low_thrust_v2_calibration_oracle", path
    )
    if spec is None or spec.loader is None:
        raise ImportError("cannot load LowThrustTransfer-v2 oracle")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _zero_policy(_initial, _target, _mass, _thrust, _isp, _duration, n_segments):
    return np.zeros((int(n_segments), 7), dtype=float)


def _input_key(initial, target, mass, thrust, isp, duration, n_segments):
    values = np.concatenate((
        np.asarray(initial, dtype=float), np.asarray(target, dtype=float),
        np.asarray((mass, thrust, isp, duration, n_segments), dtype=float),
    ))
    return values.tobytes()


def _stored_policy(oracle, coefficients):
    mapping = {}
    for public, rows in zip(oracle.public_instances(), coefficients):
        key = _input_key(
            public["initial_elements"], public["target_elements"],
            public["initial_mass_kg"], public["maximum_thrust_n"],
            public["specific_impulse_s"], public["duration_s"],
            public["n_segments"],
        )
        mapping[key] = np.asarray(rows, dtype=float)

    def policy(initial, target, mass, thrust, isp, duration, n_segments):
        key = _input_key(
            initial, target, mass, thrust, isp, duration, n_segments
        )
        if key not in mapping:
            raise ValueError("unknown public calibration instance")
        return mapping[key].copy()

    return policy


def _reference_policy(oracle):
    mapping = {}
    for instance in oracle._instances():
        public = {
            "initial_elements": instance["initial_elements"],
            "target_elements": instance["target_elements"],
            "initial_mass_kg": instance["initial_mass_kg"],
            "maximum_thrust_n": instance["maximum_thrust_n"],
            "specific_impulse_s": instance["specific_impulse_s"],
            "duration_s": instance["duration_s"],
            "n_segments": oracle.N_SEGMENTS,
        }
        mapping[_input_key(
            public["initial_elements"], public["target_elements"],
            public["initial_mass_kg"], public["maximum_thrust_n"],
            public["specific_impulse_s"], public["duration_s"],
            public["n_segments"],
        )] = np.asarray(instance["reference_coefficients"], dtype=float)

    def policy(initial, target, mass, thrust, isp, duration, n_segments):
        return mapping[_input_key(
            initial, target, mass, thrust, isp, duration, n_segments
        )].copy()

    return policy


def _cartesian_to_mee(position, velocity, mu):
    """Independent classical-elements route back to prograde Walker MEE."""
    position = np.asarray(position, dtype=float)
    velocity = np.asarray(velocity, dtype=float)
    radius = float(np.linalg.norm(position))
    angular_momentum = np.cross(position, velocity)
    h_norm = float(np.linalg.norm(angular_momentum))
    eccentricity_vector = np.cross(velocity, angular_momentum) / mu - position / radius
    eccentricity = float(np.linalg.norm(eccentricity_vector))
    p = h_norm * h_norm / mu
    inclination = math.acos(np.clip(angular_momentum[2] / h_norm, -1.0, 1.0))
    node = np.asarray((-angular_momentum[1], angular_momentum[0], 0.0))
    node_norm = float(np.linalg.norm(node))
    raan = math.atan2(node[1], node[0]) if node_norm > 1.0e-13 else 0.0
    if eccentricity > 1.0e-13 and node_norm > 1.0e-13:
        argument = math.atan2(
            np.dot(np.cross(node, eccentricity_vector), angular_momentum)
            / (node_norm * eccentricity * h_norm),
            np.dot(node, eccentricity_vector) / (node_norm * eccentricity),
        )
        anomaly = math.atan2(
            np.dot(np.cross(eccentricity_vector, position), angular_momentum)
            / (eccentricity * radius * h_norm),
            np.dot(eccentricity_vector, position) / (eccentricity * radius),
        )
    elif eccentricity > 1.0e-13:
        argument = math.atan2(eccentricity_vector[1], eccentricity_vector[0])
        anomaly = math.atan2(
            np.cross(eccentricity_vector, position)[2] / (eccentricity * radius),
            np.dot(eccentricity_vector, position) / (eccentricity * radius),
        )
        raan = 0.0
    else:
        argument = 0.0
        if node_norm > 1.0e-13:
            anomaly = math.atan2(
                np.dot(np.cross(node, position), angular_momentum)
                / (node_norm * radius * h_norm),
                np.dot(node, position) / (node_norm * radius),
            )
        else:
            anomaly = math.atan2(position[1], position[0])
    longitude_of_periapsis = raan + argument
    tangent = math.tan(0.5 * inclination)
    return np.asarray((
        p,
        eccentricity * math.cos(longitude_of_periapsis),
        eccentricity * math.sin(longitude_of_periapsis),
        tangent * math.cos(raan), tangent * math.sin(raan),
        raan + argument + anomaly,
    ))


def _independent_control(row, longitude):
    sine, cosine = math.sin(longitude), math.cos(longitude)
    return np.asarray((
        row[1] * sine + row[2] * cosine,
        row[0] + row[3] * sine + row[4] * cosine,
        row[5] * sine + row[6] * cosine,
    ))


def _cartesian_derivative(oracle, state, row, scenario):
    position = state[:3]
    velocity = state[3:6]
    mass = float(state[6])
    radius = float(np.linalg.norm(position))
    radial = position / radius
    angular_momentum = np.cross(position, velocity)
    normal = angular_momentum / np.linalg.norm(angular_momentum)
    transverse = np.cross(normal, radial)
    mee = _cartesian_to_mee(position, velocity, oracle.MU_EARTH_M3_S2)
    control = _independent_control(row, mee[5])
    thrust_acceleration = (
        float(scenario["maximum_thrust_n"]) / mass
        * (control[0] * radial + control[1] * transverse + control[2] * normal)
    )
    z_ratio_squared = float(position[2] ** 2 / radius ** 2)
    factor = (
        1.5 * oracle.J2_EARTH * oracle.MU_EARTH_M3_S2
        * oracle.EARTH_RADIUS_M ** 2 / radius ** 5
    )
    j2_acceleration = factor * np.asarray((
        position[0] * (5.0 * z_ratio_squared - 1.0),
        position[1] * (5.0 * z_ratio_squared - 1.0),
        position[2] * (5.0 * z_ratio_squared - 3.0),
    ))
    gravity = -oracle.MU_EARTH_M3_S2 * position / radius ** 3
    mass_rate = (
        -float(scenario["maximum_thrust_n"]) * float(np.linalg.norm(control))
        / (float(scenario["specific_impulse_s"]) * oracle.G0_M_S2)
    )
    return np.concatenate((velocity, gravity + j2_acceleration + thrust_acceleration,
                           np.asarray((mass_rate,))))


def _independent_cartesian_propagation(oracle, scenario, coefficients,
                                       step_limit_s=900.0):
    position, velocity = oracle.mee_to_cartesian(scenario["initial_elements"])
    initial_state = np.concatenate((
        position, velocity, (scenario["initial_mass_kg"],)
    ))
    duration = float(scenario["duration_s"])
    segment_duration = duration / oracle.N_SEGMENTS
    def derivative(time, state):
        segment = min(
            oracle.N_SEGMENTS - 1,
            int(min(float(time) / duration, 1.0 - 1.0e-15) * oracle.N_SEGMENTS),
        )
        return _cartesian_derivative(
            oracle, state, coefficients[segment], scenario
        )

    solution = solve_ivp(
        derivative,
        (0.0, duration),
        initial_state,
        method="DOP853",
        rtol=2.0e-10,
        atol=np.asarray((1.0e-3, 1.0e-3, 1.0e-3,
                         1.0e-6, 1.0e-6, 1.0e-6, 1.0e-8)),
        max_step=float(step_limit_s),
        t_eval=np.asarray((duration,)),
    )
    if not solution.success or solution.y.shape != (7, 1):
        raise RuntimeError("independent Cartesian propagation failed")
    state = solution.y[:, -1]
    return {
        "elements": _cartesian_to_mee(
            state[:3], state[3:6], oracle.MU_EARTH_M3_S2
        ),
        "mass_kg": float(state[6]),
    }


def _propagation_checks(oracle):
    checks = []
    original_step = oracle.INTEGRATION_STEP_S
    try:
        for index, scenario in enumerate(oracle._instances()):
            coefficients = np.asarray(scenario["reference_coefficients"], dtype=float)
            oracle.INTEGRATION_STEP_S = 1800.0
            production = oracle._propagate(scenario, coefficients)["state"]
            oracle.INTEGRATION_STEP_S = 900.0
            refined = oracle._propagate(scenario, coefficients)["state"]
            independent = _independent_cartesian_propagation(
                oracle, scenario, coefficients, step_limit_s=900.0
            )
            refined_scaled_error = np.abs(
                (production[:5] - refined[:5]) / scenario["terminal_scales"]
            )
            cartesian_scaled_error = np.abs(
                (refined[:5] - independent["elements"][:5])
                / scenario["terminal_scales"]
            )
            checks.append({
                "public_instance_index": index,
                "production_vs_refined_max_scaled_error": float(np.max(
                    refined_scaled_error
                )),
                "refined_vs_cartesian_max_scaled_error": float(np.max(
                    cartesian_scaled_error
                )),
                "production_vs_refined_phase_error_rad": float(oracle._wrap_angle(
                    production[5] - refined[5]
                )),
                "refined_vs_cartesian_phase_error_rad": float(oracle._wrap_angle(
                    refined[5] - independent["elements"][5]
                )),
                "refined_vs_cartesian_mass_error_kg": float(
                    refined[6] - independent["mass_kg"]
                ),
                "passed": bool(
                    np.max(refined_scaled_error) < 0.05
                    and np.max(cartesian_scaled_error) < 0.01
                    and abs(refined[6] - independent["mass_kg"]) < 5.0e-4
                ),
            })
    finally:
        oracle.INTEGRATION_STEP_S = original_step
    return checks


def _point_mass_invariant_checks(oracle):
    checks = []
    zero = np.zeros((oracle.N_SEGMENTS, 7), dtype=float)
    for index, scenario in enumerate(oracle._instances()):
        result = oracle._propagate(scenario, zero, shift={"j2": False})["state"]
        element_error = float(np.max(np.abs(
            result[:5] - scenario["initial_elements"][:5]
        )))
        mass_error = float(abs(result[6] - scenario["initial_mass_kg"]))
        checks.append({
            "public_instance_index": index,
            "maximum_first_five_element_error": element_error,
            "mass_error_kg": mass_error,
            "passed": element_error == 0.0 and mass_error == 0.0,
        })
    return checks


def _control_checks(oracle, coefficient_rows, label):
    checks = []
    for index, coefficients in enumerate(coefficient_rows):
        coefficients = np.asarray(coefficients, dtype=float)
        validated, maximum = oracle._validate_coefficients(coefficients)
        checks.append({
            "label": label,
            "public_instance_index": index,
            "shape": list(validated.shape),
            "maximum_all_longitude_throttle": float(maximum),
            "passed": bool(maximum <= 1.0),
        })
    return checks


def _invalid_checks(oracle):
    artifacts = {
        "wrong_shape": np.zeros((3, 7)),
        "nonfinite": np.full((4, 7), np.nan),
        "coefficient_bound": np.full((4, 7), 1.26),
        "continuous_thrust_bound": np.asarray(
            [[0.8, 0.8, 0.0, 0.0, 0.0, 0.0, 0.0]] * 4
        ),
    }
    checks = []
    for label, artifact in artifacts.items():
        result = oracle.evaluate(lambda *_args, value=artifact: value)
        passed = bool(
            result["valid"] == 0.0 and result["combined_score"] == 0.0
            and result["feasibility_rate"] == 0.0
            and all(not row["valid"] for row in result["per_instance"])
        )
        checks.append({
            "case": label,
            "combined_score": result["combined_score"],
            "valid": result["valid"],
            "feasibility_rate": result["feasibility_rate"],
            "passed": passed,
        })
    return checks


def calibrate():
    oracle = _load_oracle()
    baseline = oracle.evaluate(_zero_policy)
    reachability = oracle.evaluate(_reference_policy(oracle))
    classical = oracle.evaluate(_stored_policy(oracle, CLASSICAL_COEFFICIENTS))
    propagation_checks = _propagation_checks(oracle)
    point_mass_checks = _point_mass_invariant_checks(oracle)
    control_checks = (
        _control_checks(
            oracle,
            [row["reference_coefficients"] for row in oracle._instances()],
            "target_construction_reachability",
        )
        + _control_checks(oracle, CLASSICAL_COEFFICIENTS, "public_gauss_newton")
    )
    invalid_checks = _invalid_checks(oracle)

    classical_gate = bool(
        classical["valid"] == 1.0
        and classical["feasibility_rate"] == 1.0
        and classical["heldout_mission_feasibility_rate"] == 1.0
        and 0.40 < classical["combined_score"] < 0.90
        and 0.40 < classical["heldout_policy_score"] < 0.90
    )
    reachability_gate = bool(
        reachability["valid"] == 1.0
        and reachability["feasibility_rate"] == 1.0
        and reachability["heldout_mission_feasibility_rate"] == 1.0
        and reachability["development_shift_feasibility_rate"] == 1.0
        and reachability["heldout_shift_feasibility_rate"] == 1.0
        and 0.50 < reachability["combined_score"] < 0.95
    )
    execution_passed = bool(
        baseline["valid"] == 1.0
        and baseline["combined_score"] == 0.0
        and baseline["feasibility_rate"] == 0.0
        and classical_gate and reachability_gate
        and all(row["passed"] for row in propagation_checks)
        and all(row["passed"] for row in point_mass_checks)
        and all(row["passed"] for row in control_checks)
        and all(row["passed"] for row in invalid_checks)
    )
    report = {
        "schema_version": 1,
        "trust_status": "TRUSTED_TASK_CALIBRATION",
        "evidence_scope": (
            "CONTROLLED_ASTRODYNAMICS_TASK_CALIBRATION_NOT_GLOBAL_OPTIMALITY_"
            "FLIGHT_VALIDATION_MODEL_PERFORMANCE_OR_AUTONOMOUS_DISCOVERY"
        ),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "source_provenance": source_provenance(ROOT),
        "environment": {"python": sys.version, "platform": platform.platform()},
        "dimensions": {
            "public_instance_count": len(oracle.public_instances()),
            "development_instance_count": len([
                row for row in oracle._instances() if row["split"] == "development"
            ]),
            "heldout_instance_count": len([
                row for row in oracle._instances() if row["split"] == "heldout"
            ]),
            "guidance_segment_count": oracle.N_SEGMENTS,
            "coefficient_count": oracle.N_SEGMENTS * 7,
            "shift_count": len(oracle.SHIFT_SPECS),
        },
        "zero_thrust_baseline_metrics": baseline,
        "target_construction_reachability_metrics": reachability,
        "public_input_only_gauss_newton_metrics": classical,
        "classical_method": {
            "description": (
                "finite-difference regularized Gauss-Newton on the five public terminal MEE "
                "residuals, with trust-region steps and projection onto the analytic "
                "all-longitude thrust bound"
            ),
            "uses_hidden_split_or_scenario_label": False,
            "uses_hidden_target_generator_coefficients": False,
            "stored_for_deterministic_replay": True,
            "global_optimality_claimed": False,
            "runtime_benchmark_baseline": False,
            "gate_passed": classical_gate,
        },
        "reachability_gate_passed": reachability_gate,
        "production_refinement_and_independent_cartesian_checks": propagation_checks,
        "point_mass_zero_thrust_invariant_checks": point_mass_checks,
        "continuous_thrust_bound_checks": control_checks,
        "invalid_artifact_checks": invalid_checks,
        "limitations": [
            "Stored local controls demonstrate public-input solvability, not runtime generalization or global optimality.",
            "The six deterministic public missions require future server-held procedural instances.",
            "The simulator omits third bodies, drag, eclipse, power, thermal and attitude constraints.",
            "Engineering claims require independent mission-tool and domain-expert replication.",
        ],
    }
    finalize_report_trust(report, execution_passed)
    return report


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    report = calibrate()
    text = json.dumps(report, indent=2, allow_nan=False) + "\n"
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
    print(text, end="")
    return 0 if report["execution_passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
